
#lang sicp

;------------------------------------------------------------------------------------------
;EXERCISE 1.15.
;---
;The sine of an angle (specified in radians) can be computed by making use of the
;approximation sin(x)~=x if x is sufficiently small, and the trigonometric identity
;sin(x) = 3*sin(x/3) - 4*sin^3(x/3) to reduce the size of the argument of sin. (For
;purposes of this exercise an angle is considered "sufficiently small" if its magnitude
;is not greater than 0.1 radians.) These ideas are incorporated in the following
;procedures (SEE BELOW *).
;---
;a. How many times is the procedure 'p' applied when (sine 12.15) is evaluated?
;b. What is the order of growth in space and number of steps (as a function of 'a') used
;by the process generated by the 'sine' procedure when (sine a) is evaluated?
;------------------------------------------------------------------------------------------

;(*) procedures for approximating sin(x)
;---
;compute the cube of a given number x
(define (cube x) (* x x x))
;---
;compute the value of the expression 3x - 4x^3 for a given x
(define (p x) (- (* 3 x) (* 4 (cube x))))
;---
;approximate sin(x) for a given angle
(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

;answer to (a)
;---
(sine 12.15)
;(sine 12.15)
;(p (sine (/ 12.15 3.0)))
;(p (sine 4.05))
;(p (p (sine (/ 4.05 3.0))))
;(p (p (sine 1.35)))
;(p (p (p (sine (/ 1.35 3.0)))))
;(p (p (p (sine 0.45))))
;(p (p (p (p (sine (/ 0.45 3.0))))))
;(p (p (p (p (sine 0.15)))))
;(p (p (p (p (p (sine (/ 0.15 3.0)))))))
;(p (p (p (p (p (sine 0.05))))))
;(p (p (p (p (p 0.05)))))
;(p (p (p (p 0.14950000000000002))))
;(p (p (p 0.43513455050000005)))
;(p (p 0.9758465331678772))
;(p -0.7895631144708228)
;-0.39980345741334
;---
;the procedure 'p' is applied 5 times when evaluating (sine 12.15)

;answer to (b)
;---
;space complexity -> the maximum number of calls to 'p' may be computed by the expression
;angle/(3^n) < 0.1 => 0.1*3^n > angle => 3^n > 10*angle => n > log3(10*angle). hence,
;the space complexity is O(log(angle))
;---
;time complexity -> same as space complexity (the number of calls to 'p' also determines
;the number of operations performed). hence, the time complexity is O(log(angle))

