
#lang sicp

;------------------------------------------------------------------------------------------
;EXERCISE 3.11.
;---
;In Section 3.2.3 we saw how the environment model described the behavior of procedures
;with local state. Now we have seen how internal definitions work. A typical
;message-passing procedure contains both of these aspects. Consider the bank account
;procedure of Section 3.1.1:
;---
;(define (make-account balance)
;  (define (withdraw amount)
;    (if (>= balance amount)
;        (begin (set! balance (- balance amount))
;               balance)
;        "Insufficient funds"))
;  (define (deposit amount)
;    (set! balance (+ balance amount))
;    balance)
;  (define (dispatch m)
;    (cond ((eq? m 'withdraw) withdraw)
;          ((eq? m 'deposit) deposit)
;          (else
;           (error "Unknown request: MAKE-ACCOUNT"
;                  m))))
;  dispatch)
;---
;Show the environment structure generated by the sequence of interactions
;---
;(define acc (make-account 50))
;((acc 'deposit) 40) -> 90
;((acc 'withdraw) 60) -> 30
;---
;Where is the local state for 'acc' kept? Suppose we define another account
;---
;(define acc2 (make-account 100))
;---
;How are the local states for the two accounts kept distinct? Which parts of the
;environment structure are shared between 'acc' and 'acc2'?
;------------------------------------------------------------------------------------------


;ENVIRONMENT STRUCTURE
;---
;- 1. definition of 'make-account' and 'acc'
;- 2. request of 'make-deposit' and deposit of 40 monetary units
;- 3. environemnt structure after deposit
;- 4. request of 'make-withdraw' and withdraw of 60 monetary units
;- 5. environment structure after withdraw
;---
; global ---> +---------------------------------------------------------+
; env         | make-account -----------------------------------+       | <-----+
;             | acc                                             |       |       |
;             +--|----------------------------------------------|-------+       |
;                |                ↑                             |               |
;                |                |      +--- E1                ↓               |  
;                |                |      |                  +---+---+           |
;                |                |      ↓                  | | | --------------+
;                |    +----------------------+              +-|-+---+
;                |    | balance: 50          |                |
;                |    | make-deposit ---------------+         ↓
;                |    | make-withdraw ------------+ |       parameters: balance
;                |    | dispatch ---------------+ | |       body: (...)
;                |    +----------------------+  | | |
;                ↓               ↑     ↑ ↑ ↑    | | |
;            +---+---+           |     | | |    | | |
;            | | | --------------+     | | |    ↓ ↓ ↓
;            +-|-+---+                 | | |  +---+---+
;              |                       | | +----  | --------> parameters: amount
;              ↓                       | |    +---+---+       body: (...)
;           parameters: m              | +------  | --------> parameters: amount
;           body: (...)                |      +---+---+       body (...)
;                                      +--------  | --------> parameters: m
;                                             +---+----+      body: (...)
;---
; global ---> +---------------------------------------------------------+
; env         | make-account -----------------------------------+       | <-----+
;             | acc                                             |       |       |
;             +--|----------------------------------------------|-------+       |
;                |                ↑                             |               |
;                |                |      +--- E1                ↓               |  
;                |                |      |                  +---+---+           |
;                |                |      ↓                  | | | --------------+
;                |    +----------------------+              +-|-+---+
;                |    | balance: 50          |                |
;                |    | make-deposit: (...)  |                ↓
;                |    | make-withdraw: (...) |              parameters: balance
;                |    | dispatch: (...)      |              body: (...)
;                |    +----------------------+
;                ↓               ↑    ↑   ↑
;            +---+---+           |    |   |
;            | | | --------------+    |   +----------------+
;            +-|-+---+                |                    |
;              |                   +-------------+       +------------+
;              ↓                   | m: 'deposit |       | amount: 40 |
;           parameters: m          +-------------+       +------------+
;           body: (...)                  ↑                    ↑
;                                        |                    |
;                                        +--- E2              +--- E3
;---
; global ---> +---------------------------------------------------------+
; env         | make-account -----------------------------------+       | <-----+
;             | acc                                             |       |       |
;             +--|----------------------------------------------|-------+       |
;                |                ↑                             |               |
;                |                |      +--- E1                ↓               |  
;                |                |      |                  +---+---+           |
;                |                |      ↓                  | | | --------------+
;                |    +----------------------+              +-|-+---+
;                |    | balance: 90          |                |
;                |    | make-deposit: (...)  |                ↓
;                |    | make-withdraw: (...) |              parameters: balance
;                |    | dispatch: (...)      |              body: (...)
;                |    +----------------------+
;                ↓               ↑
;            +---+---+           |
;            | | | --------------+
;            +-|-+---+
;              |
;              ↓
;           parameters: m
;           body: (...)
;---
; global ---> +---------------------------------------------------------+
; env         | make-account -----------------------------------+       | <-----+
;             | acc                                             |       |       |
;             +--|----------------------------------------------|-------+       |
;                |                ↑                             |               |
;                |                |      +--- E1                ↓               |  
;                |                |      |                  +---+---+           |
;                |                |      ↓                  | | | --------------+
;                |    +----------------------+              +-|-+---+
;                |    | balance: 90          |                |
;                |    | make-deposit: (...)  |                ↓
;                |    | make-withdraw: (...) |              parameters: balance
;                |    | dispatch: (...)      |              body: (...)
;                |    +----------------------+
;                ↓               ↑    ↑   ↑
;            +---+---+           |    |   |
;            | | | --------------+    |   +----------------+
;            +-|-+---+                |                    |
;              |                   +--------------+       +------------+
;              ↓                   | m: 'withdraw |       | amount: 60 |
;           parameters: m          +--------------+       +------------+
;           body: (...)                  ↑                    ↑
;                                        |                    |
;                                        +--- E2              +--- E3
;---
; global ---> +---------------------------------------------------------+
; env         | make-account -----------------------------------+       | <-----+
;             | acc                                             |       |       |
;             +--|----------------------------------------------|-------+       |
;                |                ↑                             |               |
;                |                |      +--- E1                ↓               |  
;                |                |      |                  +---+---+           |
;                |                |      ↓                  | | | --------------+
;                |    +----------------------+              +-|-+---+
;                |    | balance: 30          |                |
;                |    | make-deposit: (...)  |                ↓
;                |    | make-withdraw: (...) |              parameters: balance
;                |    | dispatch: (...)      |              body: (...)
;                |    +----------------------+
;                ↓               ↑
;            +---+---+           |
;            | | | --------------+
;            +-|-+---+
;              |
;              ↓
;           parameters: m
;           body: (...)


;LOCATION OF 'acc' LOCAL STATE
;---
;As clearly depicted in the above figures, 'acc' local state is kept in E1's sole frame.
;Such state is reflected by the local variable 'balance'.


;PORTIONS OF THE ENVIRONMENT SHARED BETWEEN 'acc' AND 'acc2'
;---
;These account objects solely share the global part of the environment structure. Upon
;the creation of the objects, two environments are generated: one keeping 'acc' local
;state and other storing 'acc2' local state. Regarding the code concerning the procedures
;'make-deposit', 'make-withdraw' and 'dispatch', refer to the following SICP's footnote:
;"Whether 'W1' [read 'acc'] and 'W2' [read 'acc2'] share the same physical code stored in
;the computer, or whether they each keep a copy of the code, is a detail of the
;implementation. For the interpreter we implement in Chapter 4, the code is in fact
;shared."

